### ISSUE TITLE
Vulnerable PRNG entropy generation.

### ISSUE THREAD

**Issue by amepebbles** [rafaelperoco/pwdgen#1]
https://github.com/rafaelperoco/pwdgen/blob/1f206c936b66dd3dd5fbe7d61e2634f058114491/main.go#L47

`rand.Seed`'s output is reproducible if the input is known and the `time` function output will always be known. If I know your credentials creation date for a give service or platform I could estimate the input used in this function that was used to generate entropy for password creation, which is a kinda serious flaw in my opinion.

O output de `rand.Seed` é reproduzível se você conhecer o input e a função `time` segue sempre um padrão. Isso significa que, se eu souber quando você criou sua conta em algum serviço ou plataforma, eu poderia estimar o input usado na sua função para gerar entropia, o que torna seu programa vulnerável na minha opinião.

**Comment by jralmaraz** [comment]
Good catch! Shallowly thinking about a possible solution (I'm not a great developer, just an infra guy with security interest :)), maybe moving from  `math/rand` to something like https://pkg.go.dev/crypto/rand would address this concern ?

Cheers!

**Comment by rafaelperoco** [comment]
Fixed.

Thank you @amepebbles and @jralmaraz for collaboration.

If you find other issues, please let me know.

**Comment by jralmaraz** [comment]
Great stuff and quick fix , nice!
